version: '3.8'

services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3
    volumes:
      - ../backend:/app
    depends_on:
      - redis

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    volumes:
      - ../frontend:/app
      - /app/node_modules

  ai-service:
    build:
      context: ../ai_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ../ai_service:/app
    environment:
      - MODEL_PATH=/app/models

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Optional: LocalAI
  localai:
    image: localai/localai:latest
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models
    environment:
      - MODELS_PATH=/models
